[package]
name = "adapter_vda5050"
version = "0.1.0"
edition = "2021"

[dependencies]
# Inherit centralized dependencies from the workspace root manifest
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rumqttc = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }