# Global settings for on-premise deployment
replicaCount: 1

image:
  repository: ghcr.io/arcturusconsulting/issem-gateway
  tag: "0.1.2"
  pullPolicy: IfNotPresent

# Factory infrastructure endpoints
envOverrides:
  plcEndpoint: "opc.tcp://127.0.0.1:4840/"
  redisUrl: "redis://redis:6379" # DO NOT CHANGE!

# [CONFIGURE THIS CORRECTLY!] Physical host paths on the client server rack
hostPaths:
  configJson: "~/issem/deploy/config.json"
  opcUaMappingJson: "~/issem/deploy/opc_ua_mapping.json"