# Global settings for on-premise deployment
replicaCount: 1

image:
  repository: ghcr.io/arcturusconsulting/issem-gateway
  tag: "0.0.0-snapshot" # The automated pipeline will update this dynamically
  pullPolicy: IfNotPresent

# Factory infrastructure endpoints
envOverrides:
  plcEndpoint: "opc.tcp://127.0.0.1:4840/"
  redisUrl: "redis://127.0.0.1:6379"

# Physical host paths on the client server rack
hostPaths:
  configJson: "/home/norrie/issem/config.json"
  pkiDir: "/home/norrie/issem/vault/acme-logistics"
  licenseJwt: "/home/norrie/issem/vault/acme-logistics/license.jwt"