# Global settings for on-premise deployment
replicaCount: 1

image:
  repository: ghcr.io/arcturusconsulting/issem-gateway
  tag: "0.0.0-snapshot" # IGNORE THIS: This is only for maintainance.
  pullPolicy: IfNotPresent

# Factory infrastructure endpoints
envOverrides:
  plcEndpoint: "opc.tcp://127.0.0.1:4840/"
  redisUrl: "redis://redis:6379" # DO NOT CHANGE!

# Physical host paths on the client server rack
hostPaths:
  configJson: "/home/norrie/issem/deploy/config.json"
  opcUaMappingJson: "/home/norrie/issem/deploy/opc_ua_mapping.json"
  pkiDir: "/home/norrie/issem/vault/acme-logistics"
  licenseJwt: "/home/norrie/issem/vault/acme-logistics/license.jwt"