[workspace]
members = [
    "issem_core",
    "adapter_vda5050",
    "driver_zenoh_ros2",
    "adapter_opc_ua"
]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.38", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
redis = { version = "0.25", features = ["tokio-comp"] }
zenoh = "1.0.0"
rumqttc = "0.24"
cdr = "0.2.4"