apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issem-gateway
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ghcr.io/arcturusconsulting/charts
    chart: issem-gateway
    targetRevision: 0.0.0-snapshot-fa39c87
    helm:
      parameters:
        - name: image.tag
          value: 0.0.0-snapshot-fa39c87

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true