apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: issem-orchestrator
  namespace: argocd
spec:
  project: default

  source:
    chart: issem-chart
    repoURL: oci://ghcr.io/arcturusconsulting
    # Tracks any automatic patch updates within the 0.1.x life cycle
    targetRevision: ^0.1.0 

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true