//! Subsystem Root: driver_zenoh_ros2
//! Encapsulates low-level Zenoh protocols, multi-tenant telemetry ingestion, 
//! and native ROS 2 CDR stream binary serialization.

pub mod ros_msg;
pub mod telemetry;
pub mod command;

use serde::Deserialize;

// Re-export common message primitives at the crate root for diagnostics
pub use ros_msg::primitives::{
    CancelGoalRequest, GoalInfo, Point3D, Pose, PoseStamped, PoseWithCovariance,
    Quaternion, RosHeader, RosOdometry, RosTime, Twist, TwistWithCovariance, Vector3D,
};

/// Master allocation footprint for initializing Southbound operations.
#[derive(Debug, Deserialize, Clone)]
pub struct ZenohDriverConfig {
    pub listen_host: String,
    pub listen_port: u16,
    pub target_amr_serials: Vec<String>,
}

/// Protocol-agnostic command variants generated by `issem_core` 
/// and processed by the downlink subsystem.
#[derive(Debug, Clone, PartialEq)]
pub enum SouthboundCommand {
    NavigateToPose {
        serial_number: String,
        x: f64,
        y: f64,
        theta: f64,
    },
    PreemptAndHalt {
        serial_number: String,
    },
}