name: Industrial Release Pipeline

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: 'v3.12.0'

    - name: Parse Semantic Version from Git Metadata
      id: parse_version
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          CLEAN_VERSION=${{ github.ref_name }}
          CLEAN_VERSION=${CLEAN_VERSION#v}
          echo "APP_VERSION=$CLEAN_VERSION" >> $GITHUB_ENV
          echo "IS_RELEASE=true" >> $GITHUB_ENV
        else
          echo "APP_VERSION=0.0.0-snapshot" >> $GITHUB_ENV
          echo "IS_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Enterprise Container Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/arcturusconsulting/issem-orchestrator:${{ env.APP_VERSION }}-${{ env.SHORT_SHA }}
          ${{ env.IS_RELEASE == 'true' && format('ghcr.io/arcturusconsulting/issem-orchestrator:{0}', env.APP_VERSION) || '' }}
          ${{ env.IS_RELEASE == 'true' && 'ghcr.io/arcturusconsulting/issem-orchestrator:latest' || '' }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Publish Helm Chart to GHCR
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
        
        helm package deploy/issem-chart \
          --version "${{ env.APP_VERSION }}-${{ env.SHORT_SHA }}" \
          --app-version "${{ env.APP_VERSION }}-${{ env.SHORT_SHA }}"
          
        helm push issem-gateway-${{ env.APP_VERSION }}-${{ env.SHORT_SHA }}.tgz oci://ghcr.io/arcturusconsulting